### ISSUE TITLE
Typo in README.rst

### ISSUE THREAD

**Issue by ghost** [arcmags/ramroot#1]
Hi ! I think you've made a typo in `README.rst` : 

"This is was designed..." 

"is" or "was" ? 

Regards.

**Comment by arcmags** [comment]
Thanks for pointing that out.
Fixed for now!

**Comment by ghost** [comment]
@arcmags for your information: 
I made the pull request [#8806](https://github.com/voidlinux/void-packages/pull/8806) to try to integrate your tool in Void linux. 
We have `mkinitcpio` in our repos, so I guess `ramroot` should work with little modification. 
;)
