### ISSUE TITLE
Deleting files from zram does not free up space from the drive = RAM

### ISSUE THREAD

**Issue by tomjtoth** [arcmags/ramroot#14]
Please add the "-o discard" tag to your mounting function. 

I recently experimented with zram on my daily driver and noticed that deleting ~1.2GB data from /tmp (/dev/zram1) does not affect the "DATA" size reported by zramctl. Added the discard to /etc/fstab solved my problem.

**Comment by arcmags** [comment]
discard option has been added in 2.0.2
