### ISSUE TITLE
[critical] ramroot --enable bricked my system :-(

### ISSUE THREAD

**Issue by hopeseekr** [arcmags/ramroot#15]
Arch Linux, current.
Linux v5.4.68-1-lts, 26 Sep 2020 [latest version]

## Before:
My `/etc/mkinitcpio.conf` 

    HOOKS="base udev autodetect keyboard keymap consolefont modconf block lvm2 filesystems fsck"

## During
![image](https://user-images.githubusercontent.com/1125541/94890118-069a6100-0444-11eb-95f2-a8baf933eb08.png)

    ==> ramroot added to /etc/mkinitcpio.conf HOOKS
    ==> Building image from preset: /etc/mkinitcpio.d/linux-lts.preset: 'default'
      -> -k /boot/vmlinuz-linux-lts -c /etc/mkinitcpio.conf -g /boot/initramfs-linux-lts.img
    ==> ERROR: Invalid config: No hooks found

## After
Several days go by. I had completely forgotten about this failure.

I rebooted Linux and, well, let's just say my `initramfs` was pretty screwed. I had no idea what was wrong, but I was able to run SystemRescueCD and restore my `btrfs` snapshots one after another until I got to one a week prior before I ran `ramroot --enable`.

Actually, this may have hosed my system during the `yay -S ramroot`.

I had NO idea what /etc/mkinitcpio.conf was prior to all this. It's still kinda fuzzy. I'm guessing it's how Arch keeps track of what custom modules to build for new kernels?

## The Problem
Here's what `ramroot` did to my /etc/mkinitcpio.conf:

    ##   This setup loads an lvm2 volume group on a usb device.
    #    HOOKS="base udev autodetect keyboard keymap consolefont modconf block lvm2 filesystems fsck"
    #
    ##   NOTE: If you have /usr on a separate partition, you MUST include the
    #    usr, fsck and shutdown hooks.
    HOOKS=()

## The Workaround
I edited it so that it became

    HOOKS=(base udev autodetect keyboard keymap consolefont modconf block lvm2 filesystems)

However, I am totally not sure if this is going to screw over other Arch upgrades in the future :-/

**Comment by hopeseekr** [comment]
Well, I just wanted to write that I did have some real success getting arcmags/ramroot installed after I manually rewrote my `/etc/mkinitcpio.conf`:

![Screenshot from 2020-10-02 07-38-56](https://user-images.githubusercontent.com/1125541/94930045-78e26400-048b-11eb-8da3-f5f067283de0.png)
Copyright © 2020 Theodore R. Smith, all rights UNRESERVED (Public Domain)

This image is 100% royalty-free, all rights UNRESERVED, free to do whatever you want with it, for both you and any other person in the Universe, human, corporate, AI, alien, etc.


Thank you, [**arcmags**](https://github.com/arcmags/), for an amazing project! [**arcmags/ramroot**](https://github.com/arcmags/ramroot/) rocks!!

**Comment by tomjtoth** [comment]
https://github.com/arcmags/ramroot/issues/2#issuecomment-347393287

I believe this comment explains better than I could

**Comment by arcmags** [comment]
This was a parsing error that happened as Linux systems switched from ``HOOKS=""`` to ``HOOKS=()``.  This should not occur again.
