### ISSUE TITLE
ramroot not working on 5.10+

### ISSUE THREAD

**Issue by c--w** [arcmags/ramroot#18]
Why does it not work? Where exactly is the problem? Are you working on it or are you waiting for some other part to fall in place?
Can anybody help with that? Maybe I can help if you point me in the right direction and it is in my power to understand the problem.

**Comment by arcmags** [comment]
Thanks for reaching out.  Right now, I'm not really sure what's failing.  I suspect it may simply be some missing kernel modules, but I haven't had much time to look into it recently.  When I first made ramroot, it was a lot of trial and error that basically required rebooting hundreds of times.   So... probably going to be some of that again.

Anyhow, if you'd like to help, one thing we could look into is anything (a module) that's been removed from the standard kernel in the past half year.  It seems like it's a zram initialization issue, but I'm really not sure.  I'm able to create zram devices in userspace after boot, which makes me think perhaps reordering the init hooks could be a solution...

**Comment by c--w** [comment]
I see that the order is after enabling: base udev ramroot block...
So maybe just put ramroot after block?
Instead of:
```
        elif [[ "$INIT_HOOKS" =~ udev ]]; then
            INIT_HOOKS="${INIT_HOOKS%udev*}udev ramroot${INIT_HOOKS#*udev}"
```
I can try putting in:
```
        elif [[ "$INIT_HOOKS" =~ block ]]; then
            INIT_HOOKS="${INIT_HOOKS%block*}block ramroot${INIT_HOOKS#*block}"
```
?
I'll try to set it up and check.

**Comment by c--w** [comment]
The above did not help but I must admit I used ramroot version 1.1.8.
Is there some improvements in the latest version that take into account newer 5+ kernel features? Because 1.1.8 also did not work on 5.6 kernel.
I will try again with the latest ramroot version.

**Comment by c--w** [comment]
This is the same issue as in the previous issue #10 - lzo has to be added to modules - either via MODULES(lzo) in mkinitcpio.conf or even better by adding:

`add_module lzo`

to /usr/lib/initcpio/install/ramroot.

Just to be clear: with the above fix I am able to enter ramroot on  **5.10.17** (kernel is compiled with **realtime bfq** patch)

**Comment by GvY85** [comment]
took a bit more than only this but I got it working, see:

https://github.com/arcmags/ramroot/issues/20

**Comment by arcmags** [comment]
lzo is now explicitly set as the compression algo and it's been added to modules via ``add_module``.
