### ISSUE TITLE
Bug in output when generating config

### ISSUE THREAD

**Issue by c--w** [arcmags/ramroot#19]
Generating config results in output:

`==> ramroot config written to %s\n`

The line:

`msg 'ramroot config written to %s\n' "$opt_output"`

should be either: 

`printf 'ramroot config written to %s\n' "$opt_output"`

or

`msg "ramroot config written to $opt_output"`

**Comment by c--w** [comment]
I know it's a very minor - miniscule bug but anyway in case you did not notice...

**Comment by arcmags** [comment]
Fixed in 2.0.2.
