### ISSUE TITLE
Is there a way to commit changes live?

### ISSUE THREAD

**Issue by shirotech** [arcmags/ramroot#23]
Great project, it is very useful. Was wondering if there was a way to commit changes while the system is loaded in RAM? According to the readme, currently, the only way to commit changes is to disable the feature on boot?

Similar to a feature called lbu from Alpine linux: https://wiki.alpinelinux.org/wiki/Alpine_local_backup

**Comment by RadicalEd360** [comment]
There is a way.

I have created a USB project that does exactly this
with this project at its core, It works very well.
[feel free to check it out](https://github.com/RadicalEd360/ArchUSB)

while loaded into RAM the live filesystem will be under /dev/zram.
your original media will be available under the usual /dev/sdX.

To make changes to the original filesystem while running from RAM,
all you need to do is mount your media,
then arch-chroot to install packages, upgrade, remake initcpio etc.

**Comment by RadicalEd360** [comment]
it may also be convienient to use rsync to copy only the new/changed files from the live filesystem into the mounted filesystem.
I will be writing a script to do this within the next ArchUSB release.

**Comment by arcmags** [comment]
As @RadicalEd360 writes above, you can update your system while in ram by mounting and chrooting.

As far as adding some functionality to do this automatically via rsync, I don't think I will be adding this to ramroot at this time as it is out of the scope of this project.  (Perhaps with the next major version/rewrite I may do something.)
