### ISSUE TITLE
It isn't working

### ISSUE THREAD

**Issue by BbrbP** [arcmags/ramroot#25]
I dunno why

**Comment by arcmags** [comment]
I don't know why either if you cannot provide any information.

It works exactly as expected on a clean install with the latest version of Arch Linux: 6.10.10.arch1-1.

**Comment by BbrbP** [comment]
> I don't know why either if you cannot provide any information.
> 
> It works exactly as expected on a clean install with the latest version of Arch Linux: 6.10.10.arch1-1.

I'll try reinstalling arch and if that doesn't fix it, do you know how i could find out what the problem is?

**Comment by arcmags** [comment]
I could help if I had more information.

What does "It isn't working" mean?
What isn't working?
Are you unable to clone from the AUR?
Does building the package fail?
Does installing the package fail?
Are the man pages broken?
Is the configuration file broken/not being read?
Is the /etc/ramroot.z/ folder functionality not working?
Do you see a message when booting?
What isn't working?
