### ISSUE TITLE
¿Ramroot for alpine linux? (based on arch)

### ISSUE THREAD

**Issue by Klewltz** [arcmags/ramroot#26]
I can't run ramroot on alpine linux because of a bug in the code, version for alpine linux which is similar to arch?

**Comment by arcmags** [comment]
Ramroot is not compatible with Alpine Linux.  Ramroot requires [mkinitcpio](https://wiki.archlinux.org/title/Mkinitcpio) to generate its initramfs.  Alpine Linux uses [mkinitfs](https://gitlab.alpinelinux.org/alpine/mkinitfs) not mkinitcpio.
