### ISSUE TITLE
How exclude some directories?

### ISSUE THREAD

**Issue by olm52** [arcmags/ramroot#5]
How can I exclude some directories from loading to ram? For example, in a multimedia installation, I would like to exclude something like /media/music or /media/video where I would store my files.

**Comment by veggiedefender** [comment]
I would make a new partition and mount that on /media

**Comment by arcmags** [comment]
The best way would be to create a separate partition(s) for this kind of data, as suggested.  In this case you could use the `--fstab` option to mount these partitions (but not copy to RAM) on boot.

Right now there is no way to toggle specific directories, and I don't foresee myself implementing this anytime soon.  Rather the route to go would be implementing the ability to toggle specific *partitions*.
