### ISSUE TITLE
Would this work for arch arm..? [not an issue more of a question]

### ISSUE THREAD

**Issue by ghost** [arcmags/ramroot#6]
Am looking to create a small NAS using Raspberry Pi 3. Wondering if ramroot would work to at the very least run a small server then store all files to a usb device.

**Comment by arcmags** [comment]
I have not tested on Arch ARM or a Pi yet.  I suspect it would work fine; however, with only 1GB of RAM (Pi 3), your root filesystem would need to be under 500MB in order for ramroot to function.
