### ISSUE TITLE
Feature Request: --preset switch

### ISSUE THREAD

**Issue by PowerCoder** [arcmags/ramroot#8]
You're assuming every system uses the default linux-kernel. I'm using the linux-lts kernel, so the mkinitcpio command fails since it cannot find the linux.preset. The easiest fix would likely be to add the --preset/-p switch to ramroot which is then passed through to the identical switch in mkinitcpio.

The most elegant solution would be to do the same that pacman does post-install and trigger mkinitcpio for all .preset-files in order to rebuild for all installed kernels.

**Comment by arcmags** [comment]
mkinitcpio called with -P for all .preset-files in ramroot 2.0.0+
