### ISSUE TITLE
Y/N problem at boot

### ISSUE THREAD

**Issue by olm52** [arcmags/ramroot#9]
In the hot fix release did you fix the problem with Y/N at boot prompt?
Now is accepting only "yes" or "no" but not accepting "y" or "n"

**Comment by arcmags** [comment]
Hmm... I don't seem to have that problem.  If the prompt times out before you press enter, the default action will be chosen; perhaps that's the situation you're seeing?

**Comment by olm52** [comment]
No, the problem was that "n" was not recognized but only "no" but this seems fixed with the new version now. You can close.

**Comment by arcmags** [comment]
Do you think it would be better to execute the user input with the first key press?  That way the prompt would never time out if you hit y/n but haven't hit return yet.

**Comment by olm52** [comment]
Maybe is better
